name: Metrics

on:
  schedule:
    - cron: "0 3 * * *"   # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: XyraL
          template: terminal
          filename: assets/telemetry.svg
          token: ${{ secrets.GITHUB_TOKEN }}

          # Core sections
          base: header, activity, community, repositories

          # Terminal vibes
          config_display: large
          config_padding: 8%
          config_timezone: America/New_York

          # Plugins
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          plugin_followup: yes
          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact

          # Style polish
          config_octicon: yes
          config_twemoji: yes
